Integrate Wireshark 4.5.0

diff --git a/tools/update-tx b/tools/update-tx
--- a/tools/update-tx
+++ b/tools/update-tx
@@ -1,24 +1,42 @@
 #!/bin/bash
 # Copyright 2015, Alexis La Goutte (See AUTHORS file)
 #
-# Resync translation between Gerrit repo and Transifex
+# Resync translation between Wireshark's git repository and Transifex
+
+# We keep translation files in the following locations:
+# ui/qt/*.ts (Qt)
+# ui/stratoshark/*.ts (Qt)
+# packaging/debian/po/ (Gettext)
 
 NO_PUSH="False"
 while getopts "n" OPTCHAR ; do
     case $OPTCHAR in
         n) NO_PUSH="True" ;;
+        *) printf "Unknown option: %s\\n" "$OPTARG"
     esac
 done
 shift $((OPTIND - 1))
 
-# All .cpp, .h, and .ui files under ui/qt plus wireshark-qt.cpp.
-LUPDATE_FILES=$(find ui/qt -name '*.cpp' -o -name '*.h' -o -name '*.ui')
-LUPDATE_FILES=($LUPDATE_FILES wireshark-qt.cpp)
+TOP_LEVEL=$(git rev-parse --show-toplevel)
+if ! cd "$TOP_LEVEL" ; then
+    echo "Can't change to the top-level source directory."
+    exit 1
+fi
+
+LUPDATE_INCLUDES=(-I .)
+while read -r ; do
+    LUPDATE_INCLUDES+=(-I "$REPLY")
+done < <(find "$TOP_LEVEL/ui/qt" -type d)
+
+# All .cpp, .h, and .ui files under ui/qt
+LUPDATE_FILES=()
+while read -r ; do
+    LUPDATE_FILES+=("$REPLY")
+done < <(find ui/qt -name '*.cpp' -o -name '*.h' -o -name '*.ui')
 
 # Add line numbers
 for i in ui/qt/*.ts ; do
-    # shellcheck disable=SC2086
-    lupdate -locations absolute ${LUPDATE_FILES} -ts "$i"
+    lupdate -locations absolute "${LUPDATE_INCLUDES[@]}" "${LUPDATE_FILES[@]}" -ts "$i"
 done
 
 # Get last translation for Transifex
@@ -26,8 +44,7 @@ tx pull -f
 
 # Regenerate last translation for repo
 for i in ui/qt/*.ts ; do
-    # shellcheck disable=SC2086
-    lupdate -locations absolute ${LUPDATE_FILES} -ts "$i"
+    lupdate -locations absolute "${LUPDATE_INCLUDES[@]}" "${LUPDATE_FILES[@]}" -ts "$i"
 done
 
 # Push last change tranlastion on Transifex
@@ -37,15 +54,8 @@ fi
 
 # Remove line numbers
 for i in ui/qt/*.ts ; do
-    # shellcheck disable=SC2086
-    lupdate -locations none -no-ui-lines ${LUPDATE_FILES} -ts "$i"
+    lupdate -locations none -no-ui-lines "${LUPDATE_INCLUDES[@]}" "${LUPDATE_FILES[@]}" -ts "$i"
 done
-
-#Add new commit with last translaation update
-#git commit -a -m "TX: Update Translations (sync)"
-
-#Push update translation on Gerrit
-#git push origin HEAD:refs/for/master/tx
 
 #
 #  Editor modelines
